[build]
builder = "nixpacks"
buildCommand = "cd dashboard && npm install && npm run build"

[deploy]
startCommand = "cd dashboard && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
